name: save ip address

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 blep job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Get current IP address
        run: |
          curl http://ipinfo.io/ip -o ip.txt
      - name: Commit IP address file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add ip.txt
          git commit -m "Add IP address" -a || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
